//fetch appointment
export const FETCH_APPOINTMENT_REQUEST = 'FETCH_APPOINTMENT_REQUEST';
export const FETCH_APPOINTMENT_SUCCESS = 'FETCH_APPOINTMENT_SUCCESS';
export const FETCH_APPOINTMENT_FAILURE = 'FETCH_APPOINTMENT_FAILURE';

//post appointment
export const POST_APPOINTMENT_REQUEST = 'POST_APPOINTMENT_REQUEST';
export const POST_APPOINTMENT_SUCCESS = 'POST_APPOINTMENT_SUCCESS';
export const POST_APPOINTMENT_FAILURE = 'POST_APPOINTMENT_FAILURE';

//updat appointment
export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';

//delete appointment
export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST';
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS';
export const DELETE_APPOINTMENT_FAILURE = 'DELETE_APPOINTMENT_FAILURE';