//fetch notifications
export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE';

//updat notifications
export const UPDATE_NOTIFICATION_REQUEST = 'UPDATE_NOTIFICATION_REQUEST';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE';

//fetch reyal time data
export const FETCH_REAL_TIME_NOTIFICATION = 'FETCH_REAL_TIME_APPO';

//check websoket
export const WEBSOCKET_CONNECTED_NOTIFICATION = 'WEBSOCKET_CONNECTED_NOTIFICATION';
export const WEBSOCKET_DISCONNECTED_NOTIFICATION = 'WEBSOCKET_DISCONNECTED_NOTIFICATION';
export const WEBSOCKET_ERROR_NOTIFICATION = 'WEBSOCKET_ERROR_NOTIFICATION';
