//fetch user
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

//fetch WhatsApp user
export const FETCH_WHATSAPP_USER_REQUEST = 'FETCH_WHATSAPP_USER_REQUEST';
export const FETCH_WHATSAPP_USER_SUCCESS = 'FETCH_WHATSAPP_USER_SUCCESS';
export const FETCH_WHATSAPP_USER_FAILURE = 'FETCH_WHATSAPP_USER_FAILURE';

//fetch WhatsApp user
export const FETCH_WHATSAPP_REQUEST = 'FETCH_WHATSAPP_REQUEST';
export const FETCH_WHATSAPP_SUCCESS = 'FETCH_WHATSAPP_SUCCESS';
export const FETCH_WHATSAPP_FAILURE = 'FETCH_WHATSAPP_FAILURE';

//post user test message
export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const POST_USER_FAILURE = 'POST_USER_FAILURE';

//update user
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
